# Site settings
title: Lu Yu
baseurl: "/blog"
url: "http://jeppe.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
